dev:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  database: not_tribal_wars
  username: not_tribal_wars
  password: not_tribal_wars

prod:
  adapter: postgresql
  encoding: unicode
  pool: 5