dev:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  database: not_tribal_wars
  username: partneralliance
  password: partneralliance123

prod:
  adapter: postgresql
  encoding: unicode
  pool: 5